[package]
name = "GolfMania"
version = "0.1.0"
authors = ["Andrew Sansom <andrewsansomwork@gmail.com>"]

[[bin]]
path = "Golf Mania VS/src"

[dependencies]
GolfManiaLib = { git = "https://github.com/Andrew-College/GolfMania-RustLib.git" }